-- AlterTable
ALTER TABLE "Parent" ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "occupation" DROP NOT NULL,
ALTER COLUMN "religion" DROP NOT NULL,
ALTER COLUMN "state" DROP NOT NULL,
ALTER COLUMN "lga" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Student" ADD COLUMN     "section" TEXT,
ALTER COLUMN "state" DROP NOT NULL,
ALTER COLUMN "lga" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Teacher" ADD COLUMN     "section" TEXT,
ALTER COLUMN "state" DROP NOT NULL,
ALTER COLUMN "lga" DROP NOT NULL;
